apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-backend
  namespace: argocd
spec:
  project: aks-platform
  source:
    repoURL: https://github.com/<your-org>/<your-repo>.git
    targetRevision: main
    path: kubernetes/helm/backend
    helm:
      releaseName: backend
      valueFiles:
        - ../../values/dev/backend.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
