apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.env.environment | quote }}
  APP_VERSION: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.env.corsAllowedOrigins | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
