apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-postgres
  namespace: argocd
spec:
  project: aks-platform
  source:
    repoURL: https://github.com/<your-org>/<your-repo>.git
    targetRevision: main
    path: kubernetes/helm/postgres
    helm:
      releaseName: postgres
      valueFiles:
        - ../../values/staging/postgres.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
