{{- if .Values.secretsStoreCsi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "postgres.fullname" . }}-secrets
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: {{ .Values.secretsStoreCsi.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.secretsStoreCsi.keyvaultName | quote }}
    tenantId: {{ .Values.secretsStoreCsi.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secretsStoreCsi.secretObjects }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
        {{- end }}
  secretObjects:
    - secretName: {{ include "postgres.fullname" . }}-credentials
      type: Opaque
      data:
        {{- range .Values.secretsStoreCsi.secretObjects }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
        {{- end }}
{{- end }}
